### ISSUE TITLE
go mod vendor support

### ISSUE THREAD

**Issue by bsergean** [4kills/go-libdeflate#12]
I tried to vendor my dependencies but it failed because the libdeflate darwin library is not installed / copied over. Not sure how to fix that.

```
# github.com/4kills/go-libdeflate/native
clang: error: no such file or directory: '/xxx/vendor/github.com/4kills/go-libdeflate/native/libs/libdeflate_darwin_amd64.a'
FAIL	xxx/yyy [build failed]
```

**Comment by 4kills** [comment]
Hm, I will look into it. I guess the problem is that vendor does not correctly take third party C libraries into consideration properly.

**Comment by bsergean** [comment]
This might be hard to implement ; to be honest I am not using your library anymore, so I don't really need this to be fixed myself.

**Comment by bsergean** [comment]
Thanks for checking though.
