### ISSUE TITLE
With nil input slice, the resulting slice has capacity of the input

### ISSUE THREAD

**Issue by karelbilek** [4kills/go-libdeflate#21]
I have investigated a memory leak in my application; I traced the culprit here.

It seems that after compression, the resulting slice has capacity of the original data; so, if you retain the byte slice as-is, the memory of the size of the original is still held in memory.

That doesn't seem ideal and I don't think why would you want this.

It's fixable by simple `compressed = append([]byte{}, compressed...)` after compression. That takes some time because of the allocation and copy, but will save you a lot of memory.

**Comment by 4kills** [comment]
Thanks for bringing this up. I added a [comment](https://github.com/4kills/go-libdeflate/pull/22#issuecomment-2507740109) for your PR that needs to be adressed.
